### ISSUE TITLE
Booking Page - Booking Id is not generating 

### ISSUE THREAD

**Issue by PriyaPurushothaman** [MidhunBalan/IssueRepository#3]
https://app.intercom.com/a/apps/xhnn6n6y/respond/inbox/370317/conversations/11927917445

When we have booked appointment from Booking page it is not generating the Booking Id.

**Comment by PriyaPurushothaman** [comment]
Also, this affects the Export schedule - It is not having the Booking id column when we export the appointments.

**Comment by MidhunBalan** [comment]
Issue Fixed

**Comment by sakthi2794** [comment]
Test

**Comment by sakthi2794** [comment]
gh
