### ISSUE TITLE
Calendar sync issue

### ISSUE THREAD

**Issue by PandiSundaram** [MidhunBalan/IssueRepository#4]
Two way is not working for customers
https://app.intercom.com/a/apps/xhnn6n6y/respond/inbox/370317/conversations/11507857253

**Comment by PriyaPurushothaman** [comment]
Checked the Booking page with my own live account. It is working fine. I synced 5 staff with the same calendar and created a normal and recurring event in Google. Those time slots are not showing on the Booking page.
