### ISSUE TITLE
PAYMENT ISSUE

### ISSUE THREAD

**Issue by PandiSundaram** [MidhunBalan/IssueRepository#6]
Not able to upgrade
https://app.intercom.io/a/apps/xhnn6n6y/respond/inbox/460023/conversations/12239219474

**Comment by PandiSundaram** [comment]
https://app.intercom.io/a/apps/xhnn6n6y/respond/inbox/460023/conversations/12239219474
same issue working on it

**Comment by mayankdwivedi11** [comment]
test'asdfasdf

**Comment by mayankdwivedi11** [comment]
still checking

**Comment by mayankdwivedi11** [comment]
Issue is resolved.
